version: "3.9"

services:
  basic: &basic
    image: alpine:latest
    restart: on-failure
    stdin_open: true
    tty: true

  ansible:
    <<: *basic
    container_name: ansible
    build:
      context: ./ansible/
      dockerfile: Dockerfile
    image: ansible:v2.9
    volumes:
      - ./ansible/conf:/etc/ansible
      - type: bind
        source: ./ansible/log/ansible.log
        target: /var/log/ansible.log
    networks:
      - default-network

  php-1:
    <<: *basic
    container_name: php-1
    build:
      context: ./php/
      dockerfile: Dockerfile
    image: php:v8.0
    volumes:
      - type: bind
        source: ${PHP_INI:?err}
        target: /usr/local/etc/php/php.ini
      - web-site:/var/www/html
    networks:
      - default-network

  nginx-1:
    <<: *basic
    container_name: nginx-1
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    image: nginx:v1.19.6
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-1
    environment:
      - NGINX_APP_NAME=${APP_NAME:?err}
      - NGINX_APP_ENV=${NGINX_APP_ENV:?err}
      - NGINX_APP_DEBUG=${NGINX_APP_DEBUG:?err}
    volumes:
      - type: bind
        source: ./nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/conf/fastcgi_params
        target: /etc/nginx/fastcgi_params
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/alias:/etc/nginx/alias
      - web-site:/usr/share/nginx/html
    networks:
      - default-network

volumes:
    web-site:
      driver: local
      driver_opts:
        type: none
        device: ${WEB_PATH:?err}
        o: bind

networks:
  default-network:
    name: ${APP_NAME:?err}-network
