FROM php:8.0-fpm

# 時區設定 debian
RUN TZ=Asia/Taipei && \
	DEBIAN_FRONTEND=noninteractive && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get update -y && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends tzdata

# 安裝套件
RUN apt-get install -y git zip zlib1g-dev libzip-dev sqlite3 libsqlite3-dev && \
	# 安裝 php 套件
	docker-php-ext-install zip pdo pdo_mysql pdo_sqlite

# 安裝 composer
ENV PATH $PATH:/root/.composer/vendor/bin
ENV COMPOSER_ALLOW_SUPERUSER 1
#RUN pecl install uopz # 暫時不支援 PHP8
RUN curl --silent --show-error https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \
	composer global require laravel/installer && \
	# 複製 php.ini
	cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
